org: takanomotors
app: serverless-lambda-sandbox
service: serverless-lambda-sandbox

build:
  bundle: true
  external:
    - '@sparticuz/chromium'
  packages: external

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1

functions:
  hello:
    handler: src/hello.handle
    memorySize: 2048
    layers:
      - arn:aws:lambda:ap-northeast-1:112779468875:layer:chromium:1
    events:
      - httpApi:
          path: /
          method: get
