org: takanomotors
app: serverless-lambda-sandbox
service: serverless-lambda-sandbox

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1

functions:
  hello:
    handler: src/hello.handle
    memorySize: 128
    events:
      - httpApi:
          path: /
          method: get
